# Generated by Django 5.1 on 2024-08-14 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_ai_content_filtering', models.BooleanField(default=True)),
                ('allow_ai_error_detection', models.BooleanField(default=True)),
                ('allow_ai_malicious_code_scan', models.BooleanField(default=True)),
                ('allow_ai_programming_language_scan', models.BooleanField(default=True)),
                ('allow_repository_integration', models.BooleanField(default=True)),
                ('allow_pipeline_management', models.BooleanField(default=True)),
                ('allow_repository_management', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
